# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build release version for appstor"
  lane :release do
    increment_build_number
    update_app_identifier(
      xcodeproj: "RCE.xcodeproj",
      plist_path: "Info.plist",
      app_identifier: "cn.rongcloud.rcrtc.appstore"
    )
    get_certificates           # invokes cert
    get_provisioning_profile 
    build_app(scheme: "RCE",
            workspace: "RCE.xcworkspace",
            include_bitcode: false)
    deliver(
      submit_for_review: true,
      force: true,
      skip_metadata: true,
      skip_screenshots: true
    )
  end
end
